language: python
services:
  - mongodb
install: pip install -r requirements.txt
before_script: mongorestore dump/explainshell && mongorestore -d explainshell_tests dump/explainshell
script: make tests
